- name: Windows Update
  hosts: 192.168.6.129
    ansible_user:ansibletest
    ansible_password:AnsibleTest123!@#
    ansible_port:5986
    ansible_connection:winrm
    ansible_winrm_server_cert_validation:ignore
    ansible_winrm_transport:basic

  gather_facts: false
  tasks:
    - name: Run Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        reboot: yes