- name: Windows Update
  hosts: windows
  tasks:
    - name: Run Update
      win_updates:
        category_names: 
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        reboot: yes