- name: Windows Update
  hosts: 192.168.6.129
  gather_facts: false
  tasks:
    - name: Run Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        reboot: yes